
--QUERY 1: LOOKING AT THE TOP 10 STATES THAT MADE INCOME FROM THEIR SALES
SELECT TOP 10 State, Category, [Product Name], Sales, Profit, SUM(SALES + PROFIT) AS TOTAL_INCOME
FROM Orders$
GROUP BY State, Category, [Product Name], Sales, Profit
ORDER BY Sales DESC

--QUERY 2: APPLYING RANKS TO EACH PRODUCTS
SELECT [PRODUCT NAME], Quantity, [PRODUCT ID], [Ship Mode],
RANK () OVER (ORDER BY [PRODUCT NAME], Quantity, [PRODUCT ID], [Ship Mode]) AS RANKS
FROM Orders$
GROUP BY [PRODUCT NAME], Quantity, [PRODUCT ID], [Ship Mode]
ORDER BY [Product ID] ASC;

--QUERY 3: CALCULATE THE TOTAL SALES THAT WAS MADE IN EACH MONTH OF THE YEAR
WITH MONTHLYSALES AS(
SELECT [Customer ID], Sales, SUM(SALES/12) AS MONTHLYSALES
FROM Orders$
GROUP BY [Customer ID], Sales)
SELECT SUM(MONTHLYSALES) AS TOTAL_MONTHLY_INCOME
FROM MONTHLYSALES

--QUERY 4: IDENTIFYING THE DATE DIFFERENCE FROM THR ORDER DATE TO THE SHIPPING DATE
SELECT TOP 10 [Order Date], [Ship Date],
(SELECT DATEDIFF(DAYOFYEAR, 1,31)) AS DAYDIFF,
(SELECT DATEDIFF(WEEKDAY, 1,4)) AS WEEKDIFF,
(SELECT DATEDIFF(MONTH, 1,31)) AS MONTHDIFF,
(SELECT DATEDIFF(YEAR, '2014', '2015')) AS YEARDIFF
FROM Orders$

--QUERY 5: CALCULATE THE SUM OF SALES PLUS PROFIT TO GET THE ANNUAL REVENUE
--(USING CTE)
WITH TOTAL_INCOME AS(
SELECT [Customer ID], [Order Date], SUM(SALES + PROFIT) AS TOTAL_INCOME
FROM Orders$
GROUP BY [Customer ID], [Order Date])
SELECT SUM(TOTAL_INCOME) AS YEARLY_REVENUE
FROM TOTAL_INCOME
